# Makefile for FBA, for use with GNU make (Cygwin/MinGW)
#
# The first pass makes sure all intermediary targets are present. The second pass updates
# any targets, if necessary. (Intermediary) targets which have their own unique rules
# are generated as required.

#
#	Flags. Uncomment any of these declarations to enable their function.
#

# Specify the name of the executable file, without ".exe"
NAME		= fbasdl
EXE		= $(NAME)
INSTALLDIR	= /usr/local/games/fba/
ROMDIR		= /usr/local/share/roms/
BINDIR		= /usr/local/bin/
FILES		= fbasdl.ini gamelist.txt fb.png

# Inluclude Unicode support
#UNICODE = 1

# Check for changes in header files
DEPEND = 1

# Include symbols and other debug information in the executable
#SYMBOL = 1

# Include features for debugging drivers
# DEBUG	= 1

# Force recompilation of files that need it (i.e. use __TIME__, __DATE__, SPECIALBUILD).
FORCE_UPDATE = 1

# Use the __fastcall calling convention when interfacing with A68K/Musashi
#FASTCALL = 1

# Compress executable with upx (the DEBUG option ignores this)
# COMPRESS = 1

# Perl is available
PERL = 1



#
#	Declare variables
#

# Make a special build, pass the quoted text as comment (use FORCE_UPDATE declaration below to force recompilation of resources)
# SPECIALBUILD = "This text will appear in the property sheet of the .exe file"


ifndef	CPUTYPE
	CPUTYPE	= i686
endif

MMX	= 1

ifdef	DEBUG
	NAME := $(NAME)d
else
	NAME := $(NAME)
endif

ifeq	($(CPUTYPE),i686)
	ppro = ppro

endif

ifneq	($(CPUTYPE),i686)
	NAME := $(NAME)$(CPUTYPE)
endif

#
#	Specify paths/files
#

objdir	= obj/GNU_SDL/$(NAME)/
srcdir	= src/

alldir	= burn \
		burn/capcom \
		burn/cave \
		burn/cps3 \
		burn/megadrive \
		burn/misc \
		burn/misc/dec0 \
		burn/misc/konami \
		burn/misc/post90s \
		burn/misc/pre90s \
		burn/misc/psikyo \
		burn/misc/taito_68k \
		burn/neogeo \
		burn/pgm \
		burn/sega \
		burn/taito \
		burn/toaplan \
		burner \
		burner/sdl \
		interface \
		interface/sdl \
		cpu/a68k \
		cpu/i8039 \
		cpu/m6502 \
		cpu/m68k \
		cpu/nec \
		cpu/sh2 \
		cpu/z80 \
		generated

incdir	= $(foreach dir,$(alldir),-I$(srcdir)$(dir)) -I$(objdir)generated -I/local/include -I/include/SDL

lib	=  -static -lstdc++ -lpng -lmingw32 -Wl,-Bdynamic -lmingw32 -lSDL -lz -lopengl32 -lglu32

drvobj	=   	d_dodonpachi.o d_donpachi.o d_esprade.o d_feversos.o d_gaia.o d_guwange.o \
		d_sailormn.o d_uopoko.o \
		\
		dc_1941.o dc_3wonders.o dc_captcomm.o dc_cawing.o dc_dino.o  dc_dw.o \
		dc_ffight.o dc_forgottn.o dc_ghouls.o dc_knights.o dc_kod.o dc_megaman.o \
		dc_mercs.o dc_msword.o dc_mtwins.o dc_nemo.o dc_pang3.o dc_pnickj.o \
		dc_punisher.o dc_qad.o dc_qtono2.o dc_sf2.o dc_sf2t.o dc_sfzch.o \
		dc_slammast.o dc_strider.o dc_unsquad.o dc_varth.o dc_willow.o dc_wof.o \
		\
		dc_1944.o dc_19xx.o dc_armwar.o dc_avsp.o dc_batcir.o dc_choko.o dc_csclub.o \
		dc_cworld2j.o dc_cyb.o dc_ddsom.o dc_ddtod.o dc_dimahoo.o dc_dstlk.o \
		dc_ecofghtr.o dc_gigawing.o dc_hsf2.o dc_jyangoku.o dc_megaman2.o dc_mmancp2u.o \
		dc_mmatrix.o dc_mpang.o dc_msh.o dc_mshvsf.o dc_mvsc.o dc_nwarr.o dc_progear.o \
		dc_pzloop2.o dc_qnd.o dc_ringdest.o dc_sfa.o dc_sfa2.o dc_sfa3.o dc_sgemf.o \
		dc_spf.o dc_ssf2.o dc_ssf2t.o dc_vhunt2.o dc_vsav.o dc_vsav2.o dc_xmcota.o \
		dc_xmvsf.o \
		\
		d_cps3.o \
		\
		d_neogeo.o \
		\
		d_pgm.o \
		\
		d_hangon.o d_outrun.o d_sys16a.o d_sys16b.o d_sys18.o d_xbrd.o d_ybrd.o \
		\
	        d_batrider.o d_batsugun.o d_battleg.o d_bbakraid.o d_dogyuun.o d_hellfire.o d_kbash.o \
		d_mahoudai.o d_outzone.o d_shippumd.o d_snowbro2.o d_tekipaki.o d_truxton.o \
		d_truxton2.o d_vfive.o d_zerowing.o \
		\
		d_psikyo.o \
		\
		d_baddudes.o d_robocop.o \
		\
		d_opwolf.o d_rainbow.o d_rastan.o d_superman.o d_twinhawk.o \
		\
		d_mia.o d_tmnt.o \
		\
		d_taitoz.o \
		\
		d_4enraya.o d_1942.o d_1943.o d_ambush.o d_arkanoid.o d_bankp.o d_bombjack.o d_dotrikun.o \
		d_epos.o d_funkybee.o d_gunsmoke.o d_jack.o d_kyugo.o d_madgear.o d_meijinsn.o d_minivdr.o \
		d_mole.o d_mrdo.o d_mrflea.o d_mystston.o d_pacman.o d_pkunwar.o d_pooyan.o d_prehisle.o \
		d_quizo.o d_route16.o d_scregg.o d_solomon.o d_sys1.o d_tigerheli.o d_tnzs.o d_wallc.o \
		d_wc90.o \
		\
		d_1945kiii.o d_aerofgt.o d_biomtoy.o d_ddragon3.o d_fstarfrc.o d_galpanic.o d_hyperpac.o \
		d_kaneko16.o d_m90.o d_m92.o d_news.o d_ohmygod.o d_powerins.o d_raiden.o d_seta2.o \
		d_shadfrce.o d_tumbleb.o d_wwfwfest.o irem_cpu.o \
		\
		d_parent.o \
		\
		d_megadrive.o
	    
depobj := bzip_sdl.o conc_sdl.o config.o drv.o inpdipsw.o main.o run.o stated.o stringset.o \
		\
		unzip.o cong.o dat.o gamc.o gami.o \
		misc.o sshot.o state.o statec.o zipfn.o \
		\
		aud_sdl.o inp_sdl.o vid_interface_sdl.o vid_sdlfx.o vid_sdlopengl.o \
		\
		aud_dsp.o aud_interface.o inp_interface.o interface.o \
		lowpass2.o vid_softfx.o \
		vid_support.o \
		\
		$(drvobj) \
		\
		burn.o load.o cheat.o burn_gun.o \
		\
		sek.o zet.o vez.o eeprom_93cxx.o \
		burn_sound.o burn_sound_c.o timer.o \
		burn_ym2151.o burn_ym3812.o burn_ym2608.o burn_ym2610.o burn_ymf278b.o burn_ym2203.o burn_ym2612.o \
		ay8910.o ym2151.o fm.o fmopl.o ymdeltat.o \
		dac.o ics2115.o msm5205.o msm6295.o rf5c68.o segapcm.o sn76496.o upd7759.o ymf278b.o ymz280b.o \
		x1010.o \
		\
		i8039.o m6502.o m6502_intf.o nec.o sh2.o z80.o z80daisy.o \
		\
		cave.o cave_tile.o cave_sprite.o cave_palette.o \
		\
		cps.o cps_config.o cps_draw.o cps_mem.o cps_obj.o cps_pal.o cps_run.o \
		cps2_crpt.o cps_rw.o cps_scr.o cpsr.o cpsrd.o dc_input.o \
		cpst.o ctv.o ps.o ps_m.o ps_z.o qs.o qs_c.o qs_z.o \
		kabuki.o \
		\
		cps3run.o cps3snd.o \
		\
		neogeo.o neo_run.o neo_decrypt.o neo_text.o neo_sprite.o neo_palette.o neo_upd4990a.o \
		\
		pgm_crypt.o pgm_draw.o pgm_prot.o pgm_run.o \
		\
		sys16_run.o sys16_gfx.o sys16_fd1094.o fd1089.o fd1094.o mc8123.o sys16_ppi.o genesis_vid.o \
		\
		toaplan.o toa_gp9001.o toa_extratext.o toa_palette.o \
		\
		toa_bcu2.o toaplan1.o \
		\
		psikyo_tile.o psikyo_sprite.o psikyo_palette.o \
		\
		dec_aud.o dec_misc.o dec_vid.o \
		\
		rain_chip.o taito_gfx.o vid_sysx.o vid_pc080sn.o vid_pc090oj.o snd_tc0140.o \
		\
		K052109.o tmnt_inp.o tmnt_pal.o tmnt_run.o tmnt_til.o \
		\
		tc0110pcr.o tc0220ioc.o tc0150rod.o tc0140syt.o tc0100scn.o \
		\
		tiles_generic.o \
		\
		megadrive.o


autobj += $(depobj) burn_sound_a.o eagle_fm.o 2xsaimmx.o hq2x32.o hq3x32.o hq4x32.o 

autdep	= $(depobj:.o=.d)

a68k.o	= $(objdir)cpu/a68k/a68k.o

#app_windres.rc = $(srcdir)generated/app_windres.rc
#license.rc = $(srcdir)generated/license.rc
driverlist.h = $(srcdir)generated/driverlist.h
ctv.h	= $(srcdir)generated/ctv.h
toa_gp9001_func.h = $(srcdir)generated/toa_gp9001_func.h
neo_sprite_func.h = $(srcdir)generated/neo_sprite_func.h
cave_tile_func.h = $(srcdir)generated/cave_tile_func.h
cave_sprite_func.h = $(srcdir)generated/cave_sprite_func.h

allobj	= $(a68k.o) $(objdir)cpu/m68k/m68kcpu.o $(objdir)cpu/m68k/m68kopnz.o $(objdir)cpu/m68k/m68kopdm.o $(objdir)cpu/m68k/m68kopac.o $(objdir)cpu/m68k/m68kops.o \
	  $(foreach file,$(autobj:.o=.c), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .c,.o,$(wildcard $(srcdir)$(dir)/$(file))))))) \
	  $(foreach file,$(autobj:.o=.cpp), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .cpp,.o,$(wildcard $(srcdir)$(dir)/$(file))))))) \
	  $(foreach file,$(autobj:.o=.asm), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .asm,.o,$(wildcard $(srcdir)$(dir)/$(file))))))) \
	  $(foreach file,$(autobj:.o=.rc), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .rc,.o,$(wildcard $(srcdir)$(dir)/$(file)))))))

alldep	= $(foreach file,$(autobj:.o=.c), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .c,.d,$(wildcard $(srcdir)$(dir)/$(file))))))) \
	  $(foreach file,$(autobj:.o=.cpp), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .cpp,.d,$(wildcard $(srcdir)$(dir)/$(file))))))) \
	  $(foreach file,$(autobj:.o=.rc), \
		$(foreach dir,$(alldir),$(subst $(srcdir),$(objdir), \
		$(firstword $(subst .rc,.d,$(wildcard $(srcdir)$(dir)/$(file)))))))

#
#
#	Specify compiler/linker/assembler
#
#

CC	= gcc
CXX	= g++
LD	= $(CXX)
AS	= nasm

#       D3DUtils & D3DMath need these
#       DEF     = -Dsinf=\(float\)sin -Dcosf=\(float\)cos -Dasinf=\(float\)asin -Dacosf=\(float\)acos -Dsqrtf=\(float\)sqrt

CFLAGS = -O2 -fomit-frame-pointer -Wno-write-strings
CXXFLAGS = -O2 -fomit-frame-pointer -Wno-write-strings
DEF := -DCPUTYPE=$(CPUTYPE) -DUSE_SPEEDHACKS -DBUILD_SDL

ifdef SPECIALBUILD
	DEF	:= $(DEF) -DSPECIALBUILD=$(SPECIALBUILD)
endif

ifdef FASTCALL
	DEF	:= $(DEF) -DFASTCALL
endif

ifdef	DEBUG
	DEF	:= $(DEF) -D_DEBUG
endif

ifdef	MMX
	DEF	+= -DMMX
	CFLAGS += -mmmx
endif

DEF    := $(DEF) -DFILENAME=$(NAME)

ifdef PROFILE
	CFLAGS	+= -pg
else
	LDFLAGS	=
endif

CFLAGS += $(DEF) $(incdir)
CXXFLAGS += $(DEF) $(incdir)
LDFLAGS += -s
ASFLAGS = -O1

ifeq ($(OS),Windows_NT)
CFLAGS_CONSOLE = -mno-cygwin -mconsole -pipe -Wall -W $(DEF) $(incdir)
ASFLAGS += -f coff
else
ASFLAGS += -f elf
endif

#
#
#	Specify paths
#
#

vpath %.asm	$(foreach dir,$(alldir),$(srcdir)$(dir)/ )
vpath %.cpp	$(foreach dir,$(alldir),$(srcdir)$(dir)/ )
vpath %.c	$(foreach dir,$(alldir),$(srcdir)$(dir)/ )
vpath %.h	$(foreach dir,$(alldir),$(srcdir)$(dir)/ )
vpath %.rc	$(foreach dir,$(alldir),$(srcdir)$(dir)/ )

vpath %.o 	$(foreach dir,$(alldir),$(objdir)$(dir)/ )
vpath %.d 	$(foreach dir,$(alldir),$(objdir)$(dir)/ )

#
#
#	Rules
#
#

.PHONY:	all init cleandep touch clean

ifeq ($(MAKELEVEL),0)
ifdef DEPEND

all:	init $(autdep) $(autobj)
	@$(MAKE) -f makefile.test
else

all:	init $(autobj)
	@$(MAKE) -f makefile.test
endif
else

all:	$(NAME)

endif

#
#
#	Rule for linking the executable
#
#

ifeq ($(MAKELEVEL),1)

$(NAME):	$(allobj)
	@echo
	@echo Linking executable $(NAME)...
	@$(LD) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(lib)

ifdef	DEBUG

#	Don't compress when making a debug build

else
ifdef	COMPRESS
	@upx --best $@
endif
endif
endif

#
#	Generate the gamelist
#

burn.o burn.d:	driverlist.h

$(driverlist.h): $(drvobj) $(srcdir)scripts/gamelist.pl
ifdef	PERL
	@perl $(srcdir)scripts/gamelist.pl -o $@ -l gamelist.txt \
		$(filter %.cpp,$(foreach file,$(drvobj:.o=.cpp),$(foreach dir,$(alldir), \
		$(firstword $(wildcard $(srcdir)$(dir)/$(file))))))
else
ifeq ($(MAKELEVEL),1)
	@echo
	@echo Warning: Perl is not available on this system.
	@echo $@ cannot be updated or created!
	@echo
endif
endif

#
#	Fix the .rc file
#

resource.o resource.d:	$(app_windres.rc) version.rc version.h

$(license.rc): $(srcdir)license.txt $(srcdir)scripts/license2rtf.pl $(srcdir)scripts/license2rc.pl

ifdef	PERL
	@perl $(srcdir)scripts/license2rtf.pl $< -o $(srcdir)generated/$(@F:.rc=.rtf)
	@perl $(srcdir)scripts/license2rc.pl $(srcdir)generated/$(@F:.rc=.rtf) -o $@
else
ifeq ($(MAKELEVEL),1)
	@echo
	@echo Warning: Perl is not available on this system.
	@echo $@ cannot be updated or created!
	@echo
endif
endif

$(app_windres.rc): app.rc $(license.rc) $(srcdir)scripts/fixrc.pl $(srcdir)burner/resource/fba.ico $(srcdir)burner/resource/about.bmp $(srcdir)burner/resource/preview.bmp $(srcdir)burner/resource/misc.bmp

ifdef	PERL
	@perl $(srcdir)scripts/fixrc.pl $< -o $@
else
ifeq ($(MAKELEVEL),1)
	@echo
	@echo Warning: Perl is not available on this system.
	@echo $@ cannot be updated or created!
	@echo
endif
endif

#
#	Compile 68000 cores
#

# A68K

$(a68k.o):	fba_make68k.c
	@echo Compiling A68K MC68000 core...
	@$(CC) $(CFLAGS_CONSOLE) -s -DWIN32 -Wno-unused -Wno-conversion -Wno-missing-prototypes \
		-s $< -o $(subst $(srcdir),$(objdir),$(<D))/$(<F:.c=.exe)
	@$(subst $(srcdir),$(objdir),$(<D))/$(<F:.c=.exe) $(@:.o=.asm) \
		$(@D)/a68k_tab.asm 00 $(ppro)
	@echo Assembling A68K MC68000 core...
	@$(AS) $(ASFLAGS) $(@:.o=.asm) -o $@

# Musashi

$(objdir)cpu/m68k/m68kcpu.o: $(srcdir)cpu/m68k/m68kcpu.c $(objdir)generated/m68kops.h $(srcdir)cpu/m68k/m68k.h $(srcdir)cpu/m68k/m68kconf.h
	@echo Compiling Musashi MC680x0 core \(m68kcpu.c\)...
	@$(CC) $(CFLAGS) -c $(srcdir)cpu/m68k/m68kcpu.c -o $(objdir)cpu/m68k/m68kcpu.o

$(objdir)cpu/m68k/m68kops.o: $(objdir)cpu/m68k/m68kmake.exe $(objdir)generated/m68kops.h $(objdir)generated/m68kops.c $(srcdir)cpu/m68k/m68k.h $(srcdir)cpu/m68k/m68kconf.h
	@echo Compiling Musashi MC680x0 core \(m68kops.c\)...
	@$(CC) $(CFLAGS) -c $(objdir)generated/m68kops.c -o $(objdir)cpu/m68k/m68kops.o

$(objdir)cpu/m68k/m68kopac.o: $(objdir)cpu/m68k/m68kmake.exe $(objdir)generated/m68kops.h $(objdir)generated/m68kopac.c $(srcdir)cpu/m68k/m68k.h $(srcdir)cpu/m68k/m68kconf.h
	@echo Compiling Musashi MC680x0 core \(m68kopac.c\)...
	@$(CC) $(CFLAGS) -c $(objdir)generated/m68kopac.c -o $(objdir)cpu/m68k/m68kopac.o

$(objdir)cpu/m68k/m68kopdm.o: $(objdir)cpu/m68k/m68kmake.exe $(objdir)generated/m68kops.h $(objdir)generated/m68kopdm.c $(srcdir)cpu/m68k/m68k.h $(srcdir)cpu/m68k/m68kconf.h
	@echo Compiling Musashi MC680x0 core \(m68kopdm.c\)...
	@$(CC) $(CFLAGS) -c $(objdir)generated/m68kopdm.c -o $(objdir)cpu/m68k/m68kopdm.o

$(objdir)cpu/m68k/m68kopnz.o: $(objdir)cpu/m68k/m68kmake.exe $(objdir)generated/m68kops.h $(objdir)generated/m68kopnz.c $(srcdir)cpu/m68k/m68k.h $(srcdir)cpu/m68k/m68kconf.h
	@echo Compiling Musashi MC680x0 core \(m68kopnz.c\)...
	@$(CC) $(CFLAGS) -c $(objdir)generated/m68kopnz.c -o $(objdir)cpu/m68k/m68kopnz.o

$(objdir)generated/m68kops.h: $(objdir)cpu/m68k/m68kmake.exe $(srcdir)cpu/m68k/m68k_in.c
	$(objdir)/cpu/m68k/m68kmake.exe $(objdir)generated/ $(srcdir)cpu/m68k/m68k_in.c

$(objdir)cpu/m68k/m68kmake.exe: $(srcdir)cpu/m68k/m68kmake.c
	@echo Compiling Musashi MC680x0 core \(m68kmake.c\)...
	@$(CC) $(CFLAGS_CONSOLE) -s $(srcdir)cpu/m68k/m68kmake.c -o $(objdir)cpu/m68k/m68kmake.exe

#	Extra rules for generated header file cvt.h, needed by ctv.cpp
#

ctv.d ctv.o:	$(ctv.h)

$(ctv.h):	ctv_make.cpp
	@echo Generating $(srcdir)generated/$(@F)...
	@$(CXX) $(CFLAGS_CONSOLE) $(CXXFLAGS) $< \
		-o $(subst $(srcdir),$(objdir),$(<D))/$(<F:.cpp=.exe)
	@$(subst $(srcdir),$(objdir),$(<D))/$(<F:.cpp=.exe) >$@

#
#	Extra rules for generated header file toa_gp9001_func.h, needed by toa_gp9001.cpp
#

toa_gp9001.d toa_gp9001.o: $(toa_gp9001_func.h)

$(toa_gp9001_func.h):	$(srcdir)scripts/toa_gp9001_func.pl
ifdef   PERL    
	@perl $(srcdir)scripts/toa_gp9001_func.pl -o $(toa_gp9001_func.h)
else
ifeq ($(MAKELEVEL),1)
        @echo
        @echo Warning: Perl is not available on this system.
        @echo $@ cannot be updated or created!
        @echo
endif   
endif

#
#	Extra rules for generated header file neo_sprite_func.h, needed by neo_sprite.cpp
#

neo_sprite.d neo_sprite.o: $(neo_sprite_func.h)

$(neo_sprite_func.h):	$(srcdir)scripts/neo_sprite_func.pl
ifdef   PERL
	@perl $(srcdir)scripts/neo_sprite_func.pl -o $(neo_sprite_func.h)
else            
ifeq ($(MAKELEVEL),1)
        @echo
        @echo Warning: Perl is not available on this system.
        @echo $@ cannot be updated or created!
        @echo 
endif
endif

#
#	Extra rules for generated header file cave_tile_func.h, needed by cave_tile.cpp
#

cave_tile.d cave_tile.o: $(cave_tile_func.h)

$(cave_tile_func.h):	$(srcdir)scripts/cave_tile_func.pl
ifdef   PERL
	@perl $(srcdir)scripts/cave_tile_func.pl -o $(cave_tile_func.h)
else            
ifeq ($(MAKELEVEL),1)
        @echo
        @echo Warning: Perl is not available on this system.
        @echo $@ cannot be updated or created!
        @echo 
endif
endif

#
#	Extra rules for generated header file cave_sprite_func.h, needed by cave_sprite.cpp
#

cave_sprite.d cave_sprite.o: $(cave_sprite_func.h)

$(cave_sprite_func.h):	$(srcdir)scripts/cave_sprite_func.pl
ifdef   PERL
	@perl $(srcdir)scripts/cave_sprite_func.pl -o $(cave_sprite_func.h)
else            
ifeq ($(MAKELEVEL),1)
        @echo
        @echo Warning: Perl is not available on this system.
        @echo $@ cannot be updated or created!
        @echo 
endif
endif

ifeq ($(MAKELEVEL),1)
ifdef DEPEND

include	$(alldep)

endif
endif

#
#	Generic rule for resource files
#

%.o:	%.rc
	@echo Compiling resource file $(<F)...
	@windres $(DEF) $< -o $(subst $(srcdir),$(objdir),$(<D))/$(@F) $(foreach dir,$(alldir),--include-dir $(srcdir)$(dir))

#
#	Generic rules for C/C++ files
#

ifeq ($(MAKELEVEL),0)

ifdef FORCE_UPDATE
resource.o: FORCE
about.o: FORCE
endif

%.o:	%.cpp
	@echo Compiling $<...
	@$(CXX) $(CXXFLAGS) -c $< -o $(subst $(srcdir),$(objdir),$(<D))/$(@F)

%.o:	%.c
	@echo Compiling $<...
	@$(CC) $(CFLAGS) -Wno-unused -Wno-conversion -Wno-missing-prototypes -c $< -o $(subst $(srcdir),$(objdir),$(<D))/$(@F)

%.o:	%.asm
	@echo Assembling $<...
	@$(AS) $(ASFLAGS) $< -o $(subst $(srcdir),$(objdir),$(<D))/$(@F)

else

%.o:	%.c
	@echo Compiling $<...
	@$(CC) $(CFLAGS) -Wno-unused -Wno-conversion -Wno-missing-prototypes -c $< -o $@

%.o:	%.asm
	@echo Assembling $<...
	@$(AS) $(ASFLAGS) $< -o $@

%.o:
	@echo Compiling $<...
	@$(CC) $(CXXFLAGS) -c $< -o $@

endif

#
#	Generate dependencies for C/C++ files
#

ifdef DEPEND

%.d:	%.c
	@echo Generating depend file for $<...
	@$(CC) -MM -MT "$(subst $(srcdir),$(objdir),$(<D))/$(*F).o $(subst $(srcdir),$(objdir),$(<D))/$(@F)" -x c++ $(CFLAGS) $< >$(subst $(srcdir),$(objdir),$(<D))/$(@F)

%.d:	%.cpp
	@echo Generating depend file for $<...
	@$(CXX) -MM -MT "$(subst $(srcdir),$(objdir),$(<D))/$(*F).o $(subst $(srcdir),$(objdir),$(<D))/$(@F)" -x c++ $(CFLAGS) $< >$(subst $(srcdir),$(objdir),$(<D))/$(@F)

%.d:	%.rc
	@echo Generating depend file for $<...
	@$(CC) -MM -MT "$(subst $(srcdir),$(objdir),$(<D))/$(*F).o $(subst $(srcdir),$(objdir),$(<D))/$(@F)" -x c++ $(CFLAGS) $< >$(subst $(srcdir),$(objdir),$(<D))/$(@F)

endif

#
#	Phony targets
#

init:

ifdef	DEBUG
	@echo Making debug build...
else
	@echo Making normal build...
endif
	@echo
	@mkdir -p $(foreach dir, $(alldir),$(objdir)$(dir))
	@mkdir -p $(srcdir)generated

cleandep:
	@echo Removing depend files from $(objdir)...
	@for dir in $(alldir); do rm -f $(objdir)$$dir/*.d; done

touch:
	@echo Marking all targets for $(NAME) as uptodate...
	@for dir in $(alldir); do touch -c $(objdir)$$dir/*; done
	@do touch -c $(srcdir)/generated/*
	@touch $(NAME).exe
install:
	mkdir -p $(INSTALLDIR)
	mkdir -p $(ROMDIR)
	cp $(EXE) $(INSTALLDIR)
	cp $(FILES) $(INSTALLDIR)
	ln -fs $(INSTALLDIR)$(EXE) $(BINDIR)$(EXE)

clean:
	@echo Removing all files from $(objdir)...
	@rm -f -r $(objdir)
	@rm -f -r $(ctv.h)

ifdef	PERL
	@echo Removing all files generated with perl scripts...
	@rm -f -r $(app_windres.rc) $(driverlist)
endif
	@echo Removing executable file...
	@rm -f $(EXE)

#
#	Rule to force recompilation of any target that depends on it
#

FORCE:
